name: Build resume site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: actions/checkout@v2

    - name: Install wkhtmltopdf
      run: |
          apt-get update -y
          apt-get install xvfb libfontconfig1 wkhtmltopdf -y

    - uses: actions/setup-node@v1
      with:
        node-version: '12.6'

    - name: Install npm dependencies
      run: npm install

    # Build pdf
    - name: Build pdf
      run: npm run build_resume_pdf

    # Build site
    - name: Build the site
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
