name: Build resume site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: actions/checkout@v2

    - name: Install wkhtmltopdf
      run: |
          if ! [ -x "$(command -v sudo)" ]; then
            echo 'Installing sudo for running local actions with `act`.' >&2
            apt-get update -y
            apt-get install sudo -y
          fi
          sudo apt-get update -y
          sudo apt-get install xvfb libfontconfig1 wkhtmltopdf -y

    - uses: actions/setup-node@v1
      with:
        node-version: '12.6'

    - name: Install npm dependencies
      run: npm install

    # Build pdf
    # We run it through xvfb-run due to a bug in headless mode, in debian's version of wkhtmltopdf
    # https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037#issuecomment-62019521
    - name: Build pdf
      run: xvfb-run -- npm run build_resume_pdf

    # Build site
    - name: Build the site
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
