name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm ci

    # Build pdf
    - name: Build pdf
      run: npm run build_resume_pdf

    # Build site
    - name: Build the site
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: balbona.me
